apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword-app-deployment
  labels:
    app: helloword-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: helloword-app
  template:
    metadata:
      labels:
        app: helloword-app
    spec:
      containers:
        - name: helloword-app
          image: michalp96/helloworld-dev:latest  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: helloword-app-service
spec:
  selector:
    app: helloword-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
  type: LoadBalancer  
