apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: michalp96/helloworld-dev:latest  # Replace with your Docker image 
          ports:
            - containerPort: 3000  # Adjust the port if your Node.js app listens on a different port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80  # External port for accessing the service
      targetPort: 3000  # Port on the pods where your Node.js app is running
  type: LoadBalancer  # Use LoadBalancer for cloud deployments (e.g., AWS, GCP), or NodePort for on-premises
